/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapturaRouteImport } from './routes/captura'
import { Route as CasaRouteImport } from './routes/casa'
import { Route as ConselhosRouteImport } from './routes/conselhos'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as ParcelasRouteImport } from './routes/parcelas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaRoute = CapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaRoute = CasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConselhosRoute = ConselhosRouteImport.update({
  id: '/conselhos',
  path: '/conselhos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelasRoute = ParcelasRouteImport.update({
  id: '/parcelas',
  path: '/parcelas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captura': typeof CapturaRoute
  '/casa': typeof CasaRoute
  '/conselhos': typeof ConselhosRoute
  '/extrato': typeof ExtratoRoute
  '/parcelas': typeof ParcelasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captura': typeof CapturaRoute
  '/casa': typeof CasaRoute
  '/conselhos': typeof ConselhosRoute
  '/extrato': typeof ExtratoRoute
  '/parcelas': typeof ParcelasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captura': typeof CapturaRoute
  '/casa': typeof CasaRoute
  '/conselhos': typeof ConselhosRoute
  '/extrato': typeof ExtratoRoute
  '/parcelas': typeof ParcelasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/captura' | '/casa' | '/conselhos' | '/extrato' | '/parcelas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/captura' | '/casa' | '/conselhos' | '/extrato' | '/parcelas'
  id:
    | '__root__'
    | '/'
    | '/captura'
    | '/casa'
    | '/conselhos'
    | '/extrato'
    | '/parcelas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapturaRoute: typeof CapturaRoute
  CasaRoute: typeof CasaRoute
  ConselhosRoute: typeof ConselhosRoute
  ExtratoRoute: typeof ExtratoRoute
  ParcelasRoute: typeof ParcelasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura': {
      id: '/captura'
      path: '/captura'
      fullPath: '/captura'
      preLoaderRoute: typeof CapturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa': {
      id: '/casa'
      path: '/casa'
      fullPath: '/casa'
      preLoaderRoute: typeof CasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conselhos': {
      id: '/conselhos'
      path: '/conselhos'
      fullPath: '/conselhos'
      preLoaderRoute: typeof ConselhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelas': {
      id: '/parcelas'
      path: '/parcelas'
      fullPath: '/parcelas'
      preLoaderRoute: typeof ParcelasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapturaRoute: CapturaRoute,
  CasaRoute: CasaRoute,
  ConselhosRoute: ConselhosRoute,
  ExtratoRoute: ExtratoRoute,
  ParcelasRoute: ParcelasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
